version: "3"

services:
  mysql:
    image: mysql:8.3.0
    networks:
      - default
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./ops/db/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
      MYSQL_USER: server
      MYSQL_PASSWORD: senhaserver

